AWSTemplateFormatVersion: 2010-09-09
Description: "lecture10_template"

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
Parameters:
  DBMasterUserName:
    Type: String
    NoEcho: true
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: "must begin with a letter and contain only alphanumeric characters."
  
  DBPassword:
    NoEcho: true
    Type: String
    MinLength: 8
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: "must contain only alphanumeric characters."

# application
# ------------------------------------------------------------#
#  EC2 SecurityGroup
# ------------------------------------------------------------#
Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: lecture10-EC2SG
      GroupDescription: lecture10-EC2SG
      VpcId: !ImportValue VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: '-1'  # 全てのアウトバウンド通信を許可
          CidrIp: '0.0.0.0/0'
      Tags:
        - Key: !ImportValue tagkeyID
          Value: lecture10-ec2SecurityGroup

# ------------------------------------------------------------#
#  IAM
# ------------------------------------------------------------#
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal: 
              Service: 
                - ec2.amazonaws.com
            Action: 
              - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      RoleName: lecture10-role
      Tags:
        - Key: !ImportValue tagkeyID
          Value: lecture10-IAMrole

  IAMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: lecture10-instanceprofile
      Roles: 
        - !Ref IAMRole

# ------------------------------------------------------------#
#  EC2 Instance
# ------------------------------------------------------------#
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: RaiseTech
      ImageId: ami-0190c0073f61fb37a
      InstanceType: t2.small
      Monitoring: false
      IamInstanceProfile: !Ref IAMInstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !ImportValue PublicSubnet1ID
          GroupSet:
          - !Ref EC2SecurityGroup
      Tags:
        - Key: !ImportValue tagkeyID
          Value: lecture10-EC2Instance

# ------------------------------------------------------------#
#  RDS SecurityGroup
# ------------------------------------------------------------#
  RDSSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: !ImportValue VPCID
      GroupName: rds-sg
      GroupDescription: lecture10-rds-sg
      Tags:
        - Key: !ImportValue tagkeyID
          Value: lecture10-rds-sg
# Rule
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref EC2SecurityGroup
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref EC2SecurityGroup

# ------------------------------------------------------------#
#  RDS SubnetGroup
# ------------------------------------------------------------#
  RDSSubnetGroup: 
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupName: rds-SubnetGroup
      DBSubnetGroupDescription: lecture10-subnetGP
      SubnetIds: 
        - !ImportValue PrivateSubnet1ID
        - !ImportValue PrivateSubnet2ID

# ------------------------------------------------------------#
#  RDS create
# ------------------------------------------------------------#
  RDSInstance: 
    Type: "AWS::RDS::DBInstance"
    Properties: 
      DBInstanceIdentifier: lectutre10-rds
      Engine: MySQL
      EngineVersion: "8.0.35"
      DBInstanceClass: db.t3.micro
      AllocatedStorage: "20"
      StorageType: gp2
      MasterUsername: !Ref DBMasterUserName
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref RDSSubnetGroup
      AvailabilityZone: ap-northeast-1a
      PubliclyAccessible: false
      MultiAZ: false
      AutoMinorVersionUpgrade: false
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      CopyTagsToSnapshot: true
      BackupRetentionPeriod: 0
      Tags: 
        - Key: !ImportValue tagkeyID
          Value: lecture10-RDS
      
# ------------------------------------------------------------#
#  ALB security
# ------------------------------------------------------------#
  ALBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: lecture10-alb-security
      GroupDescription: lecture10-alb-security
      VpcId: !ImportValue VPCID # ALBを配置するVPCのID
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"  # HTTPアクセスをインターネットから許可（ポート80）
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: "0.0.0.0/0"  # すべてのトラフィックを許可（アウトバウンド）

# ------------------------------------------------------------#
#  ALB TargetGroup
# ------------------------------------------------------------#
  ALBTargetGroup: 
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Name: lecture10-albtg
      VpcId: !ImportValue VPCID
      Protocol: HTTP
      Port: 80
      TargetType: instance
      HealthCheckPath: "/"
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      HealthCheckTimeoutSeconds: 5
      HealthCheckIntervalSeconds: 30
      Matcher:
        HttpCode: 200
      Targets:
        - Id: !Ref EC2Instance
          Port: 80
      Tags:
        - Key: !ImportValue tagkeyID
          Value: lecture10-albtg

# ------------------------------------------------------------#
#  ALB create
# ------------------------------------------------------------#
  ALB:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: "lecture10-alb"
      Subnets:
        - !ImportValue PublicSubnet1ID # ALBが配置されるサブネットID
        - !ImportValue PublicSubnet2ID
      SecurityGroups:
        - !Ref ALBSecurityGroup  # セキュリティグループID
      Scheme: internet-facing  # インターネット経由のトラフィックを受ける場合は "internet-facing"
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'  # アイドルタイムアウト（秒）
      Type: application  # ALBの場合は"application"
      IpAddressType: ipv4  # IPアドレスのタイプ（ipv6も設定可能）

# ------------------------------------------------------------#
#  ALB listener
# ------------------------------------------------------------#
  ALBListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP

# ------------------------------------------------------------#
#  S3 create
# ------------------------------------------------------------#
  S3:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: lecture10-mybucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: !ImportValue tagkeyID
          Value: lecture10-s3